### ISSUE TITLE
className is not a supported attribute

### ISSUE THREAD

**Issue by csi-lk** [stagas/vdomini#1]
`className` is commonly used over class in jsx to avoid conflicting with the `class` javascript keyword

render doesn't seem to support this

input

```jsx
<div className="foo">Text</div>
```

output

```jsx
<div classname="foo">Text</div>
```

expected

```jsx
<div class="foo">Text</div>
```

**Comment by stagas** [comment]
The properties in jsx are passed as an object and `class` is allowed as a property name. The aim of the project is to be copy-paste compatible with html code. This project also is abandoned because it has irrepairable architecture error when dealing with functional components. It's been superceded by [this one](https://github.com/stagas/html-vdom) which is simpler. Thanks for checking it out.
